{
  context.stopProcess();
  boolean shouldLog=true;
  Throwable cause=th;
  while (true) {
    if (unloggedExceptionClasses.contains(cause.getClass().getName())) {
      shouldLog=false;
      break;
    }
    cause=cause.getCause();
    if (cause == null) {
      break;
    }
  }
  if (shouldLog) {
    LOG.error("An error occurred during the workflow",th);
  }
  throw new WorkflowException(th);
}
